### ISSUE TITLE
Default payment method behaviour

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/whmcs-bitcoin-plugin#135]
- How does WHMCS decide default payment method for loggedin / non logged in users
- Merchant wants to retain default payment method as credit card

### Payment methods
<img width="985" alt="3  gateway" src="https://user-images.githubusercontent.com/22165583/144002766-b407e03b-85aa-4c8b-8488-da4ab70621c3.png">

### Before Login
<img width="694" alt="1  before login" src="https://user-images.githubusercontent.com/22165583/144002821-f46fd3e7-d262-4e9e-9409-277df86f0298.png">

### After Login
<img width="675" alt="2  after login" src="https://user-images.githubusercontent.com/22165583/144002824-bfdf8ebe-cb89-4bab-b201-9405e82ddacd.png">

**Comment by thisisayush** [comment]
Hi,

This issue is more of a WHMCS issue rather than a plugin issue. WHMCS selects the first available Payment Gateway Configured in settings as default in the Checkout screen for both logged in and guest users.

Ref: https://requests.whmcs.com/idea/default-payment-gateway

Are you using any addon for changing the default payment gateway or overriding it on per client/service basis?
